// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3tIyDmc97ssmUr_eEnDRQn0PpvZZREb4',
    appId: '1:655104687890:android:98aa275de55cadf5debdcb',
    messagingSenderId: '655104687890',
    projectId: 'hellochickgu-15c69',
    authDomain: 'hellochickgu-15c69.firebaseapp.com',
    storageBucket: 'hellochickgu-15c69.firebasestorage.app',
    //measurementId: 'G-52RMQVE2SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3tIyDmc97ssmUr_eEnDRQn0PpvZZREb4',
    appId: '1:655104687890:android:98aa275de55cadf5debdcb',
    messagingSenderId: '655104687890',
    projectId: 'hellochickgu-15c69',
    storageBucket: 'hellochickgu-15c69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3tIyDmc97ssmUr_eEnDRQn0PpvZZREb4',
    appId: '1:655104687890:android:98aa275de55cadf5debdcb',
    messagingSenderId: '655104687890',
    projectId: 'hellochickgu-15c69',
    storageBucket: 'hellochickgu-15c69.firebasestorage.app',
    iosBundleId: 'com.example.hellochickgu',
  );
}

// firebase config
