// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDk4CoDqoT0Ohg9OVeaTV-0aJMMRW3rqU',
    appId: '1:864651268854:web:ef8e6d24d079af4c6b92d7',
    messagingSenderId: '864651268854',
    projectId: 'hellochickgu',
    authDomain: 'hellochickgu.firebaseapp.com',
    storageBucket: 'hellochickgu.firebasestorage.app',
    measurementId: 'G-52RMQVE2SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNjptoLfeMUBnD2OzaGzigFuq3M5hfKLo',
    appId: '1:864651268854:android:a20b384092f4b73a6b92d7',
    messagingSenderId: '864651268854',
    projectId: 'hellochickgu',
    storageBucket: 'hellochickgu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCObKj3adDCVT14ETZuANWfakXknlgSb1I',
    appId: '1:864651268854:ios:5243364a1dfbc68b6b92d7',
    messagingSenderId: '864651268854',
    projectId: 'hellochickgu',
    storageBucket: 'hellochickgu.firebasestorage.app',
    iosBundleId: 'com.example.hellochickgu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCObKj3adDCVT14ETZuANWfakXknlgSb1I',
    appId: '1:864651268854:ios:5243364a1dfbc68b6b92d7',
    messagingSenderId: '864651268854',
    projectId: 'hellochickgu',
    storageBucket: 'hellochickgu.firebasestorage.app',
    iosBundleId: 'com.example.hellochickgu',
  );
}
